### ISSUE TITLE
Routing: weird routing

### ISSUE THREAD

**Issue by pietervdvn** [anyways-open/genk-cycling-frontend#33] opened 2019-03-11 15:25 UTC
https://genk.anyways.eu/staging/?loc1=5.487959,50.963906&loc2=5.468838,50.952335&zoom=13.54&lat=50.956950&lng=5.487207&p=network-genk&

![Screenshot from 2019-03-11 16-21-40](https://user-images.githubusercontent.com/1466478/54135555-52c52100-441a-11e9-8258-21e1d087bf27.png)
![Screenshot from 2019-03-11 16-22-47](https://user-images.githubusercontent.com/1466478/54135562-56f13e80-441a-11e9-9d92-64f8116ee454.png)

**Comment by xivk** [comment] 2019-03-12 17:40
This is probably because there is an error in the mapping:

https://www.openstreetmap.org/relation/9052448#map=15/50.9517/5.4735&layers=C
https://www.openstreetmap.org/relation/9052728#map=14/50.9420/5.4669&layers=C

This should fix things:

https://www.openstreetmap.org/changeset/68071576#map=15/50.9498/5.4580&layers=C

To check in 24hrs.

**Comment by xivk** [comment] 2019-03-14 12:33
Still a weird thing but the mapping was fixed:

![image](https://user-images.githubusercontent.com/1128068/54357126-42e55100-4655-11e9-8bef-32e0d049dc16.png)

This is a duplicate of https://github.com/anyways-open/cycling-backend/issues/11

**Closed by xivk** 2019-03-14 12:33 UTC
Labels: bug
